name: airchat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: ">=2.7.0 <3.0.0"

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.2.4
  qrscan: ^0.3.2
  cloud_firestore: ^2.4.0
  firebase_core: ^1.4.0

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

